
@info = {
	"about" => "I am an ambitious and motivated individual who is currently working for the Civil Service but looking to pursue a career in web development.
Since graduating from Loughborough University in 2010 - where I studied Politics and Economics - I have gone on to work in a variety of different positions within the financial, legal, and retail service industries. This experience has allowed me to build my professional and communication skills, which I am now looking to utilize within a more rewarding and suitable role.
",
	"web_track_completedness" => "100",
	"ruby_track_completedness" => "100",
	"js_track_completedness" => "100",
	"why_apply" => "Once I had decided to learn web development, enrolling in a coding bootcamp seemed like the most sensible and pragmatic option available to me, given their fast-paced teaching style and the opportunities that they can create. Of all the bootcamps that I have researched since making this decision, We Got Coders stood out to me because of its small class size and culture of immersive and collaborative learning. The curriculum aligns flawlessly with my programming interests and career goals, and the prospect of being able to go straight into employment afterwards appeals to me greatly. I operate best when I'm working in a structured environment with like-minded, motivated people, and We Got Coders offers a great opportunity to do this. I would also like to study in a peaceful location without the stress of having to find short-term accommodation and the distraction of commuting to class every day. These reasons, along with the intensity of the program, make me feel as though the course would be the perfect choice for me."
	"where_in_1" => "In 1 year's time I would like to be a confident and capable Ruby developer, working for a professional organisation and gaining the practical experience needed in order to take my knowledge of the subject to the next level. I would also like to be working on my own personal projects in order to build up an attractive portfolio which I could be proud to present to employers. Finally, I would like to have the confidence and grounding to go on to learn other programming languages in order to make myself a more versatile and employable developer."
}